# Generated by Django 4.2.29 on 2026-03-14 14:10

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('advisors', '0002_alter_advisor_hire_date_alter_advisor_id'),
        ('listings', '0002_auto_20200325_0007'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='advisor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='advisors.advisor'),
        ),
        migrations.AlterField(
            model_name='listing',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='listing',
            name='list_date',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now),
        ),
    ]
